Merged from upstream

diff --git a/bin/mysql-workbench-schema-export b/bin/mysql-workbench-schema-export
--- a/bin/mysql-workbench-schema-export
+++ b/bin/mysql-workbench-schema-export
@@ -49,10 +49,11 @@ const CMD_OPT_HELP           = 'help';
 function showTitle()
 {
     $version = FormatterInterface::VERSION;
+    $year = date('Y');
     echo <<<EOF
 MySQL Workbench Schema Exporter version $version.
-Copyright (c) 2010-2014 Johannes Mueller <circus2@web.de>
-Copyright (c) 2012-2014 Toha <tohenk@yahoo.com>
+Copyright (c) 2010-{$year} Johannes Mueller <circus2@web.de>
+Copyright (c) 2012-{$year} Toha <tohenk@yahoo.com>
 
 
 EOF;
@@ -69,7 +70,7 @@ Usage:
 $self [options] FILENAME [DEST]
 
 Options:
---export=type       Select the exporter, for a list of available exportor
+--export=type       Select the exporter, for a list of available exporter
                     use --list-exporter option.
 --config=file       Read file for export parameters, in JSON format.
 --saveconfig        Save export parameters to file.
@@ -107,8 +108,7 @@ function parseCmdLine($args = array(), &$params = array(), &$options = array(), 
                 }
             }
             if (!$found) {
-                echo sprintf("Unknown option %s.\n", $arg);
-                die(1);
+                throw new InvalidArgumentException(sprintf("Unknown option %s.\n", $arg));
             }
         } else {
             $values[] = $arg;
@@ -197,17 +197,35 @@ function setupFormatter(&$setup, $validators)
     }
 }
 
-function listFormatter($bootstrap, $ordered = false)
+function listFormatter($bootstrap, $ordered = false, $title = null)
 {
-    $i = 0;
-    $formatters = $bootstrap->getFormatters();
-    // find the longest formatter name
-    $len = max(array_map('strlen', array_keys($formatters))) + 1;
-    $nlen = strlen((string) count($formatters));
-    foreach ($formatters as $name => $class) {
-        $i++;
-        $formatter = $bootstrap->getFormatter($name);
-        echo sprintf("%s %-${len}s %s\n", $ordered ? str_pad((string) $i, $nlen, ' ', STR_PAD_LEFT).'.' : '-', $name, $formatter->getTitle());
+    if (count($formatters = $bootstrap->getFormatters())) {
+        if ($ordered) {
+            ksort($formatters);
+        }
+        // find the longest formatter name
+        $len = max(array_map('strlen', array_keys($formatters))) + 1;
+        $nlen = strlen((string) count($formatters));
+        if ($title) {
+            echo "$title\n";
+        }
+        $i = 0;
+        foreach ($formatters as $name => $class) {
+            $i++;
+            $formatter = $bootstrap->getFormatter($name);
+            echo sprintf("%s %-${len}s %s\n", $ordered ? str_pad((string) $i, $nlen, ' ', STR_PAD_LEFT).'.' : '-', $name, $formatter->getTitle());
+        }
+    } else {
+        echo <<<EOF
+No exporter found.
+
+Exporter are separate projects which need to be installed via composer.
+You can find all exporters at https://github.com/mysql-workbench-schema-exporter.
+
+Example:
+  php composer.phar require --dev mysql-workbench-schema-exporter/doctrine2-exporter
+
+EOF;
     }
 
     return $formatters;
@@ -230,147 +248,143 @@ function chooseFormatter($bootstrap)
 
 function main($filename, $dir, $params, $options)
 {
-    try {
-        showTitle();
+    showTitle();
 
-        // check the existance of filename
-        if (!is_readable($filename)) {
-            echo sprintf("Can't find document %s.\n\n", $filename);
-            die(1);
+    // bootstrap
+    $bootstrap = new Bootstrap();
+    if ($options[CMD_OPT_LIST_EXPORTER]) {
+        listFormatter($bootstrap, true, 'Supported exporter:');
+        die(0);
+    }
+
+    // check the existance of filename
+    if (!is_readable($filename)) {
+        throw new \InvalidArgumentException(sprintf("Can't find document %s.\n\n", $filename));
+    }
+
+    $setup = array();
+    $configs = array();
+
+    // lookup config file export.json
+    if (!$options[CMD_OPT_NO_AUTO_CONFIG] && !$params[CMD_PARAM_CONFIG]) {
+        $config = getcwd().DIRECTORY_SEPARATOR.'export.json';
+        if (is_readable($config)) {
+            $params[CMD_PARAM_CONFIG] = $config;
         }
+    }
 
-        $setup = array();
-        $configs = array();
-
-        // bootstrap
-        $bootstrap = new Bootstrap();
-        if ($options[CMD_OPT_LIST_EXPORTER]) {
-            echo "Supported exporter:\n";
-            listFormatter($bootstrap, true);
-            die(0);
-        }
-
-        // lookup config file export.json
-        if (!$options[CMD_OPT_NO_AUTO_CONFIG] && !$params[CMD_PARAM_CONFIG]) {
-            $config = getcwd().DIRECTORY_SEPARATOR.'export.json';
-            if (is_readable($config)) {
-                $params[CMD_PARAM_CONFIG] = $config;
+    // check config file
+    if ($config = $params[CMD_PARAM_CONFIG]) {
+        if (!is_readable($config)) {
+            echo sprintf("Can't read config file %s, using interactive mode.\n\n", $config);
+        } elseif (null !== ($data = json_decode(file_get_contents($config), true))) {
+            echo sprintf("Using config file %s for parameters.\n\n", $config);
+            if (isset($data[CMD_PARAM_EXPORT])) {
+                $params[CMD_PARAM_EXPORT] = $data[CMD_PARAM_EXPORT];
             }
-        }
-
-        // check config file
-        if ($config = $params[CMD_PARAM_CONFIG]) {
-            if (!is_readable($config)) {
-                echo sprintf("Can't read config file %s, using interactive mode.\n\n", $config);
-            } else {
-                if (null !== ($data = json_decode(file_get_contents($config), true))) {
-                    echo sprintf("Using config file %s for parameters.\n\n", $config);
-                    if (isset($data[CMD_PARAM_EXPORT])) {
-                        $params[CMD_PARAM_EXPORT] = $data[CMD_PARAM_EXPORT];
-                    }
-                    if (isset($data[CMD_OPT_ZIP])) {
-                        $options[CMD_OPT_ZIP] = (bool) $data[CMD_OPT_ZIP];
-                    }
-                    if (isset($data['dir'])) {
-                        $dir = $data['dir'];
-                    }
-                    if (isset($data['params'])) {
-                        $configs = $data['params'];
-                    }
-                } else {
-                    echo sprintf("Ignoring invalid config file %s.\n\n", $config);
-                }
+            if (isset($data[CMD_OPT_ZIP])) {
+                $options[CMD_OPT_ZIP] = (bool) $data[CMD_OPT_ZIP];
             }
-        }
-
-        // choose exporter to use if not specified
-        if (null === $params[CMD_PARAM_EXPORT]) {
-            // choose exporter to use
-            echo "Choose which exporter to use:\n";
-            $params[CMD_PARAM_EXPORT] = chooseFormatter($bootstrap);
-            echo "\n";
-        }
-
-        // get formatter after getting the parameter export either from command line or config file
-        if (!$formatter = $bootstrap->getFormatter($params[CMD_PARAM_EXPORT])) {
-            echo sprintf("Unsupported exporter %s. Use --%s option to show all available exporter.", $params[CMD_PARAM_EXPORT], CMD_OPT_LIST_EXPORTER);
-            die(1);
-        }
-
-        // parameters customization
-        echo sprintf("Exporting %s as %s.\n\n", basename($filename), $formatter->getTitle());
-        $setup = $formatter->getConfigurations();
-        if (count($configs)) {
-            mergeFormatter($setup, $configs);
+            if (isset($data['dir'])) {
+                $dir = $data['dir'];
+            }
+            if (isset($data['params'])) {
+                $configs = $data['params'];
+            }
         } else {
-            $ask = false;
-            askValue('Would you like to change the setup configuration before exporting', $ask);
-            if ($ask) {
-                setupFormatter($setup, $formatter->getValidators());
-            }
-            echo "\n";
+            echo sprintf("Ignoring invalid config file %s.\n\n", $config);
         }
+    }
 
-        // save export parameters
-        if ($options[CMD_OPT_SAVE_CONFIG]) {
-            file_put_contents('export.json', json_encode(
-                array(
-                    CMD_PARAM_EXPORT => $params[CMD_PARAM_EXPORT], 
-                    CMD_OPT_ZIP => $options[CMD_OPT_ZIP], 
-                    'dir' => $dir, 'params' => $setup
-                )
-            ));
+    // choose exporter to use if not specified
+    if (null === $params[CMD_PARAM_EXPORT]) {
+        // choose exporter to use
+        echo "Choose which exporter to use:\n";
+        $params[CMD_PARAM_EXPORT] = chooseFormatter($bootstrap);
+        echo "\n";
+    }
+
+    // get formatter after getting the parameter export either from command line or config file
+    if (!$formatter = $bootstrap->getFormatter($params[CMD_PARAM_EXPORT])) {
+        throw new \InvalidArgumentException(sprintf("Unsupported exporter %s. Use --%s option to show all available exporter.", $params[CMD_PARAM_EXPORT], CMD_OPT_LIST_EXPORTER));
+    }
+
+    // parameters customization
+    echo sprintf("Exporting %s as %s.\n\n", basename($filename), $formatter->getTitle());
+    $setup = $formatter->getConfigurations();
+    if (count($configs)) {
+        mergeFormatter($setup, $configs);
+    } else {
+        $ask = false;
+        askValue('Would you like to change the setup configuration before exporting', $ask);
+        if ($ask) {
+            setupFormatter($setup, $formatter->getValidators());
         }
+        echo "\n";
+    }
 
-        // start time
-        $start = microtime(true);
+    // save export parameters
+    if ($options[CMD_OPT_SAVE_CONFIG]) {
+        file_put_contents('export.json', json_encode(
+            array(
+                CMD_PARAM_EXPORT => $params[CMD_PARAM_EXPORT],
+                CMD_OPT_ZIP => $options[CMD_OPT_ZIP],
+                'dir' => $dir, 'params' => $setup
+            ),
+            JSON_PRETTY_PRINT
+        ));
+    }
 
-        // parse the mwb file
-        $formatter->setup($setup);
-        $document = $bootstrap->export($formatter, $filename, $dir, $options[CMD_OPT_ZIP] ? 'zip' : 'file');
+    // start time
+    $start = microtime(true);
 
-        // end time
-        $end = microtime(true);
+    // parse the mwb file
+    $formatter->setup($setup);
+    $document = $bootstrap->export($formatter, $filename, $dir, $options[CMD_OPT_ZIP] ? 'zip' : 'file');
 
-        if ($document) {
-            echo sprintf("File exported to %s.\n\n", $document->getWriter()->getStorage()->getResult());
-            // show some information about used memory
-            // show the time needed to parse the mwb file
-            echo sprintf("Done in %0.3f second, %0.3f MB memory used.\n", $end - $start, memory_get_peak_usage(true) / 1024 / 1024);
-            die(0);
-        } else {
-            echo "Export failed, may be there is no storage available.\n\n";
-            die(1);
-        }
-    } catch (\Exception $e) {
-        echo "Error:\n";
-        echo $e->getMessage();
-        die(1);
+    // end time
+    $end = microtime(true);
+
+    if ($document) {
+        echo sprintf("File exported to %s.\n\n", $document->getWriter()->getStorage()->getResult());
+        // show some information about used memory
+        // show the time needed to parse the mwb file
+        echo sprintf("Done in %0.3f second, %0.3f MB memory used.\n", $end - $start, memory_get_peak_usage(true) / 1024 / 1024);
+        die(0);
+    } else {
+        throw new Exception("Export failed, may be there is no storage available.");
     }
 }
 
 // ----------------------------------------- MAIN ---------------------------------------------------- //
 
-// default values
-$arguments = $_SERVER['argv'];
-$options = array(
-    CMD_OPT_HELP           => false,
-    CMD_OPT_ZIP            => false,
-    CMD_OPT_SAVE_CONFIG    => false,
-    CMD_OPT_LIST_EXPORTER  => false,
-    CMD_OPT_NO_AUTO_CONFIG => false,
-);
-$params = array(
-    CMD_PARAM_EXPORT        => null,
-    CMD_PARAM_CONFIG        => null,
-);
+try {
+    // default values
+    $arguments = $_SERVER['argv'];
+    $options = array(
+        CMD_OPT_HELP           => false,
+        CMD_OPT_ZIP            => false,
+        CMD_OPT_SAVE_CONFIG    => false,
+        CMD_OPT_LIST_EXPORTER  => false,
+        CMD_OPT_NO_AUTO_CONFIG => false,
+    );
+    $params = array(
+        CMD_PARAM_EXPORT        => null,
+        CMD_PARAM_CONFIG        => null,
+    );
 
-array_shift($arguments);
-parseCmdLine($arguments, $params, $options, $values);
-if ($options[CMD_OPT_HELP] || (count($values) < 1) && !$options[CMD_OPT_LIST_EXPORTER]) {
-    usage();
+    array_shift($arguments);
+    parseCmdLine($arguments, $params, $options, $values);
+    if ($options[CMD_OPT_HELP] || (count($values) < 1) && !$options[CMD_OPT_LIST_EXPORTER]) {
+        usage();
+    }
+
+    main(count($values) ? $values[0] : null, count($values) > 1 ? $values[1] : getcwd(), $params, $options);
+
+} catch (\Exception $e) {
+    echo "Error:\n";
+    echo $e->getMessage();
+    die(1);
 }
-
-main(count($values) ? $values[0] : null, count($values) > 1 ? $values[1] : getcwd(), $params, $options);
 
 // ----------------------------------------- EOF ----------------------------------------------------- //
